- name: Set Prompt
  ansible.builtin.shell: set-prompt prometheus
- name: create prometheus user
  ansible.builtin.user:
    name: prometheus
- name: Download prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true
    owner: prometheus
    group: prometheus
- name: Update Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.52.0.linux-amd64/prometheus.yml
    owner: prometheus
    group: prometheus
- name: Copy Prometheus systemd file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes