- name: Set Prompt
  ansible.builtin.shell: set-prompt prometheus
- name: create prometheus user
  ansible.builtin.user:
    name: prometheus
- name: Download prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true