# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
        # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'expense-project-nodes'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Monitor"
            values: ["yes"]
    relabel_configs:
{%for label in labels%}
      - source_labels: [__meta_ec2_{{label}}]
        target_label: {{label}}
{%endfor%}
  - job_name: 'nginx exporter nodes'
    ec2_sd_configs:
        - region: us-east-1
          port: 9113
          filters:
            - name: "tag:component"
              values: ["Frontend"]
    relabel_configs:
{%for label in labels%}
    - source_labels: [__meta_ec2_{{label}}]
      target_label: {{label}}
{%endfor%}
    - job_name: 'grok exporter nodes'
      ec2_sd_configs:
        - region: us-east-1
          port: 9144
          filters:
            - name: "tag:component"
              values: ["Frontend"]
      relabel_configs:
{%for label in labels%}
    - source_labels: [__meta_ec2_{{label}}]
      target_label: {{label}}
{%endfor%}